-- =========================================================
-- Drop existing tables (run if you want a clean recreate)
-- =========================================================
DROP TABLE IF EXISTS "ListItem"          CASCADE;
DROP TABLE IF EXISTS "Media_Genres"      CASCADE;
DROP TABLE IF EXISTS "Media_Contributors" CASCADE;
DROP TABLE IF EXISTS "List"              CASCADE;
DROP TABLE IF EXISTS "Reviews"           CASCADE;
DROP TABLE IF EXISTS "Media"             CASCADE;
DROP TABLE IF EXISTS "Genres"            CASCADE;
DROP TABLE IF EXISTS "People"            CASCADE;
DROP TABLE IF EXISTS "Users"             CASCADE;

-- =========================================================
-- Base tables
-- =========================================================

CREATE TABLE "Users" (
    "UserID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserName"      TEXT        NOT NULL,
    "UserPassword"  TEXT        NOT NULL,
    "UserEmail"     TEXT        NOT NULL UNIQUE,
    "CreationDate"  TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UserRole"      TEXT,              -- enum in ERD; use TEXT or create a PostgreSQL ENUM
    "Bio"           TEXT
);

CREATE TABLE "Media" (
    "MediaID"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Type"         TEXT        NOT NULL,  -- enum in ERD
    "Title"        TEXT        NOT NULL,
    "ReleaseDate"  TIMESTAMPTZ,
    "Description"  TEXT,
    "pages"        INTEGER,
    "runtime"      INTEGER
);

CREATE TABLE "Genres" (
    "GenreID"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GenreName" TEXT NOT NULL
);

CREATE TABLE "People" (
    "PersonID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"     TEXT NOT NULL
);

-- =========================================================
-- Tables with foreign keys
-- =========================================================

CREATE TABLE "Reviews" (
    "UserID"        INTEGER NOT NULL,
    "ReviewID"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MediaID"       INTEGER NOT NULL,
    "Status"        TEXT,           -- enum in ERD
    "ProgressValue" INTEGER,
    "ProgressUnit"  TEXT,           -- enum in ERD
    "StartedOn"     TIMESTAMPTZ,
    "FinishedOn"    TIMESTAMPTZ,
    "Priority"      INTEGER,
    "Notes"         TEXT,
    "DateUpdated"   TIMESTAMPTZ,

    CONSTRAINT fk_reviews_user
        FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID"),
    CONSTRAINT fk_reviews_media
        FOREIGN KEY ("MediaID") REFERENCES "Media" ("MediaID")
);

CREATE TABLE "List" (
    "UserID"       INTEGER NOT NULL,
    "ListID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CreationDate" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "Title"        TEXT NOT NULL,
    "Description"  TEXT,

    CONSTRAINT fk_list_user
        FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID")
);

-- Junction table between List and Reviews
CREATE TABLE "ListItem" (
    "ListID"   INTEGER NOT NULL,
    "ReviewID" INTEGER NOT NULL,
    "Status"   TEXT,      -- enum in ERD

    CONSTRAINT pk_listitem
        PRIMARY KEY ("ListID", "ReviewID"),
    CONSTRAINT fk_listitem_list
        FOREIGN KEY ("ListID")   REFERENCES "List"    ("ListID")   ON DELETE CASCADE,
    CONSTRAINT fk_listitem_review
        FOREIGN KEY ("ReviewID") REFERENCES "Reviews" ("ReviewID") ON DELETE CASCADE
);

-- Junction table between Media and Genres
CREATE TABLE "Media_Genres" (
    "MediaID" INTEGER NOT NULL,
    "GenreID" INTEGER NOT NULL,

    CONSTRAINT pk_media_genres
        PRIMARY KEY ("MediaID", "GenreID"),
    CONSTRAINT fk_mg_media
        FOREIGN KEY ("MediaID") REFERENCES "Media"  ("MediaID") ON DELETE CASCADE,
    CONSTRAINT fk_mg_genre
        FOREIGN KEY ("GenreID") REFERENCES "Genres" ("GenreID") ON DELETE CASCADE
);

-- Junction table between Media and People (contributors)
CREATE TABLE "Media_Contributors" (
    "MediaID"  INTEGER NOT NULL,
    "PersonID" INTEGER NOT NULL,
    "Role"     TEXT,      -- enum in ERD

    CONSTRAINT pk_media_contributors
        PRIMARY KEY ("MediaID", "PersonID"),
    CONSTRAINT fk_mc_media
        FOREIGN KEY ("MediaID")  REFERENCES "Media"  ("MediaID")  ON DELETE CASCADE,
    CONSTRAINT fk_mc_person
        FOREIGN KEY ("PersonID") REFERENCES "People" ("PersonID") ON DELETE CASCADE
);

-- Optional: indexes to speed up common lookups (not required but useful)
CREATE INDEX idx_reviews_user   ON "Reviews" ("UserID");
CREATE INDEX idx_reviews_media  ON "Reviews" ("MediaID");
CREATE INDEX idx_list_user      ON "List"    ("UserID");
CREATE INDEX idx_listitem_review ON "ListItem" ("ReviewID");
CREATE INDEX idx_mg_genre       ON "Media_Genres" ("GenreID");
CREATE INDEX idx_mc_person      ON "Media_Contributors" ("PersonID");